# Generated by Django 5.0.6 on 2024-06-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_content_alter_message_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='private_images/'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='private_voices/'),
        ),
    ]
